name: GitHub Actions Pipeline
on: [push, workflow_dispatch]
jobs:
  backend-CI:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - run: tsc
      - run: npm test

  frontend-CI:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - run: npm install @rollup/rollup-linux-x64-gnu --save-optional
      - run: npm test

  E2E-CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Start the backend
        run: |
          cd backend &&
          npm ci &&
          npm run dev &

      - run: cd frontend && npm install @rollup/rollup-linux-x64-gnu --save-optional

      - name: Cypress run

        uses: cypress-io/github-action@v6
        with:
          working-directory: ./frontend
          start: npm run dev
